events {}

http {
    server {
        listen 443 ssl;
        server_name localhost;

	    ssl_certificate "/etc/nginx/ssl/localhost/localhost.cert.pem";
	    ssl_certificate_key "/etc/nginx/ssl/localhost/localhost.key.pem";

        location / {
            proxy_pass http://frontend-container:3000;
        }

        # 구체적인 경로를 먼저 정의 (높은 우선순위)
        location /api/v1/orders/ {
            proxy_pass http://backend-trade-container:8082;
        }

        location /api/v1/histories/ {
            proxy_pass http://backend-trade-container:8082;
        }
        
        # WebSocket 연결을 위한 broadcaster 프록시 설정
        location /ws {
            proxy_pass http://backend-broadcaster-container:8083;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_cache_bypass $http_upgrade;
        }
        
        # 일반적인 경로를 마지막에 정의 (낮은 우선순위)
        location /api/v1/ {
            proxy_pass http://backend-auth-container:8080;
        }    
    }
}