events {}

http {
    server {
        listen 80;

        location / {
            proxy_pass http://frontend-container:3000;
        }

        # 구체적인 경로를 먼저 정의 (높은 우선순위)
        location /api/v1/orders/ {
            proxy_pass http://backend-trade-container:8082;
        }

        location /api/v1/histories/ {
            proxy_pass http://backend-trade-container:8082;
        }
        
        # 일반적인 경로를 마지막에 정의 (낮은 우선순위)
        location /api/v1/ {
            proxy_pass http://backend-auth-container:8080;
        }    
    }
}