apiVersion: apps/v1
kind: Deployment
metadata:
  name: msa-auth
  namespace: cowing-prod
  labels:
    app: msa-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: msa-auth
  template:
    metadata:
      labels:
        app: msa-auth
    spec:
      containers:
        - name: msa-auth
          image: ghcr.io/coinwing/cowing-msa-auth
          readinessProbe:
          httpGet:
            path: /actuator/health
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
          imagePullPolicy: Always
          env:
            - name: REDIS_HOST
              value: "msa-auth-redis"
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: redis-password
            - name: DB_URL
              value: "jdbc:mariadb://common-mariadb/cowingDB"
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: password
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: jwt-secret
            - name: ACCESS_TOKEN_EXPIRE
              value: "86400000"
            - name: REFRESH_TOKEN_EXPIRE
              value: "172800000"
          resources:
            requests:
              cpu: "0.5"
              memory: "512Mi"
            limits:
              cpu: "0.5"
              memory: "700Mi"
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: ghcr-login-secret