apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- pending-queue-redis.yaml
- pending-queue-redis-svc.yaml
- auth-redis.yaml
- auth-redis-svc.yaml
- orderbook-redis.yaml
- orderbook-redis-svc.yaml
namespace: cowing-prod
images:
- name: ghcr.io/coinwing/cowing-msa-orderbook
  newName: ghcr.io/coinwing/cowing-msa-orderbook
  newTag: 2025.08.02-9cc711c
