apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderbook-redis
  namespace: cowing-prod
  labels:
    app: orderbook-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orderbook-redis
  template:
    metadata:
      labels:
        app: orderbook-redis
    spec:
      containers:
        - name: orderbook-redis
          image: redis:alpine
          env:
          - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-secret     
              key: redis-password   
          command: ["redis-server", "--port", "6380", "--appendonly", "no", "--save", ""]
          args: ["--requirepass", "$(REDIS_PASSWORD)"]
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 200m
              memory: 200Mi
          ports:
            - containerPort: 6380