apiVersion: apps/v1
kind: Deployment
metadata:
  name: cowing-msa-auth-deployment
  labels:
    app: cowing-msa-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cowing-msa-auth
  template:
    metadata:
      labels:
        app: cowing-msa-auth
        cowing: auth
    spec:
      containers:
        - name: cowing-msa-auth
          image: ghcr.io/coinwing/cowing-msa-auth:main
          imagePullPolicy: Always
          env:
            - name: REDIS_HOST
              value: "redis-service"
            - name: REDIS_PORT
              value: "6379"
            - name: DB_URL
              value: "jdbc:mariadb://mariadb-service:3306/cowingDB"
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mardiadb-secret
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mardiadb-secret
                  key: password
            - name: JWT_SECRET
              value: "99f461065038a0d63d66ad26d52bf68a76ad3b0d7cb576f2b67cd8d9e75230e9"
            - name: ACCESS_TOKEN_EXPIRE
              value: "86400000"
            - name: REFRESH_TOKEN_EXPIRE
              value: "172800000"
          resources:
            limits:
              memory: "700Mi"
              cpu: 500m
            requests:
              memory: "512Mi"
              cpu: 200m
          ports:
            - containerPort: 8082
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8082
            initialDelaySeconds: 180
            periodSeconds: 30
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8082
            initialDelaySeconds: 180
            periodSeconds: 15
            failureThreshold: 5
      imagePullSecrets:
        - name: ghcr-login-secret
