apiVersion: apps/v1
kind: Service
metadata:
  name: msa-auth-redis
  namespace: cowing-prod
spec:
  selector:
    app: msa-auth-redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  type: ClusterIP