apiVersion: v1
kind: Deployment
metadata:
  name: msa-auth-redis
  namespace: cowing-prod
  labels:
    app: msa-auth-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: msa-auth-redis
  template:
    metadata:
      labels:
        app: msa-auth-redis
    spec:
      containers:
        - name: msa-auth-redis
          image: redis:alpine
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: redis-password
          command: ["sh", "-c"]
          args:
            - |
              redis-server --requirepass "$REDIS_PASSWORD" --appendonly no --save ""
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 200m
              memory: 200Mi
          ports:
            - containerPort: 6379