apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: msa-auth
  namespace: argocd
  labels:
    app: msa-auth
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/CoinWing/Infrastructure.git
    path: code/argocd/kustomize/msa-auth
    targetRevision: prod
  destination:
    server: https://kubernetes.default.svc
    namespace: cowing-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
  - group: apps
    jsonPointers:
    - /spec/replicas
    - /metadata/annotations/deployment.kubernetes.io/revision
    kind: Deployment
  - group: autoscaling
    jsonPointers:
    - /status
    kind: HorizontalPodAutoscaler

