apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: msa-broadcaster
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/CoinWing/Cowing-msa-broadcaster
    path: code/argocd/kustomize/msa-broadcaster
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: cowing-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true