apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: msa-trade
  namespace: argocd
  labels:
    app: msa-trade
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/CoinWing/Infrastructure.git
    path: code/argocd/kustomize/msa-trade
    targetRevision: prod
  destination:
    server: https://kubernetes.default.svc
    namespace: cowing-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true