apiVersion: v1
kind: Service
metadata:
  name: msa-front
  namespace: cowing-prod
spec:
  type: LoadBalancer
  selector:
    app: msa-front
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
