apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: jwt-external-secret
  namespace: cowing-prod
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: jwt-secret
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        jwt-secret: "{{ .jwt_secret }}"
  data:
  - secretKey: jwt_secret
    remoteRef:
      key: cowing-prod-jwt-secret
      property: jwt_secret