apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: redis-external-secret
  namespace: cowing-prod
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: redis-secret
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        redis-password: "{{ .password }}"
  data:
  - secretKey: password
    remoteRef:
      key: cowing-prod-redis-secret
      property: password
