apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sqs-config-external-secret
  namespace: cowing-prod
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: trade-config
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        queue-name: "{{ .queue_name }}"
        pd-redis-password: "{{ .pd_redis_password }}"
        access-key: "{{ .access_key }}"
        secret-key: "{{ .secret_key }}"
        sqs-uri: "{{ .sqs_uri }}"
  data:
  - secretKey: queue_name
    remoteRef:
      key: cowing-prod-sqs-config-secret
      property: queue_name
  - secretKey: pd_redis_password
    remoteRef:
      key: cowing-prod-sqs-config-secret
      property: pd_redis_password
  - secretKey: access_key 
    remoteRef:
      key: cowing-prod-sqs-config-secret
      property: access_key
  - secretKey: secret_key
    remoteRef:
      key: cowing-prod-sqs-config-secret
      property: secret_key
  - secretKey: sqs_uri
    remoteRef:
      key: cowing-prod-sqs-config-secret
      property: sqs_uri
