apiVersion: v1
kind: Service
metadata:
  name: cowing-msa-auth-service
spec:
  selector:
    app: cowing-msa-auth
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
  type: ClusterIP
