apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- hpa.yaml
namespace: cowing-prod
images:
- name: ghcr.io/coinwing/cowing-msa-front
  newName: ghcr.io/coinwing/cowing-msa-front
  newTag: 2025.08.25-a54dd70
