name: LocalStack Terraform Test

on:
  pull_request:
    branches:
      - prod

  workflow_dispatch: 

jobs:
  localstack-terraform-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./code/terraform/dev
    steps:
    - uses: actions/checkout@v4
    
    - name: Check directory contents
      run: ls -la

    - name: Build and Start LocalStack Container
      run: |
        docker compose up -d

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: latest

    - name: Run Terraform Init and Validation
      run: |
        terraform init
        terraform validate
        terraform fmt --recursive --check --diff
        terraform plan
        terraform show

    - name: Run Terraform Test
      run: |
        terraform test

    - name: Stop and Delete LocalStack Container
      if: always()
      run: docker compose down
